- name: Installs haproxy load balancer
  apt: pkg=haproxy state=installed update_cache=yes

- name: Pushes configuration
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
  notify:
    - restart haproxy

- name: Sets default starting flag to 1
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify:
    - restart haproxy
