- hosts: all

  tasks:
    - name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
      action: command host -t A ansible.cc
      register: ns
      ignore_errors: yes

    - name: Pushes new resolver configuration if resolver fails
      action: lineinfile regexp="^nameserver " line="nameserver 8.8.8.8" dest=/etc/resolv.conf
      when_failed: $ns

    - name: Checks if resolver is working properly with new nameserver
      action: command host -t A ansible.cc
